name: Continuous Deployment

on:
  push:
    branches:
      - main

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      M365_ACCOUNT_NAME: Aadharsha@developerworks.onmicrosoft.com
      M365_ACCOUNT_PASSWORD: Testdevelopment123$
      M365_TENANT_ID: 62edfd41-1282-4e35-b9da-c6a75c0b31a9
      # To specify the env name for multi-env feature.
      TEAMSFX_ENV_NAME: dev
    steps:
      - name: Print new build number
        run: teamsfx config set interactive false

      # Login Azure by service principal 
      - uses: OfficeDev/teamsfx-cli-action@v1
        with:
          commands: account login azure 
          service-principal: true
          username: 750ac5c1-e4a6-4b0d-9a8c-dd630c940869
          password: A7~8Q~-IgNarVqj3twIJseEzqC7ssEHWJlFoQa2-
          tenant: 62edfd41-1282-4e35-b9da-c6a75c0b31a9
 
      # Provision resources.
      - uses: OfficeDev/teamsfx-cli-action@v1
        with:
          commands: package
          #subscription: ${{secrets.AZURE_SUBSCRIPTION_ID}}
          env: ${{env.TEAMSFX_ENV_NAME}}
    
      # Deploy the code.
      - uses: OfficeDev/teamsfx-cli-action@v1
        with:
          commands: deploy
          env: ${{env.TEAMSFX_ENV_NAME}}

      # Publish the Teams App.
      - uses: OfficeDev/teamsfx-cli-action@v1
        with:
          commands: publish
          env: ${{env.TEAMSFX_ENV_NAME}}
