# This is just an example workflow for provision.
# You should customize it to meet your own requirements.
name: 'Provision'

on:
  push:
    branches:
      - main
  # Manually trigger this workflow, and you should pick the right branch.
jobs:
  publishTeamsApp:
    runs-on: ubuntu-latest
    # You can uncomment the line below to use environments (refer to https://docs.github.com/en/actions/reference/environments). 
    #environment: test_environment
    # env:
    #   M365_ACCOUNT_NAME: Aadharsha@developerworks.onmicrosoft.com
    #   M365_ACCOUNT_PASSWORD: Testdevelopment123$
    #   M365_TENANT_ID: 62edfd41-1282-4e35-b9da-c6a75c0b31a9
    #   # To specify the environment name which will be used as an option below.
    #   # You can change it to use your own environment name.
    #   TEAMSFX_ENV_NAME: 'dev'
    #   # To specify the version of TTK CLI for use.
    #   TEAMSFX_CLI_VERSION: 2.*

    steps:
      # Setup environment.
      - uses: actions/setup-node@v2
        with:
          node-version: '18'
          
      - name: Checkout the code
        uses: actions/checkout@v2



 
